require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TalkaboutsController do

  # This should return the minimal set of attributes required to create a valid
  # Talkabout. As you add validations to Talkabout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TalkaboutsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all talkabouts as @talkabouts" do
      talkabout = Talkabout.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:talkabouts)).to eq([talkabout])
    end
  end

  describe "GET show" do
    it "assigns the requested talkabout as @talkabout" do
      talkabout = Talkabout.create! valid_attributes
      get :show, {:id => talkabout.to_param}, valid_session
      expect(assigns(:talkabout)).to eq(talkabout)
    end
  end

  describe "GET new" do
    it "assigns a new talkabout as @talkabout" do
      get :new, {}, valid_session
      expect(assigns(:talkabout)).to be_a_new(Talkabout)
    end
  end

  describe "GET edit" do
    it "assigns the requested talkabout as @talkabout" do
      talkabout = Talkabout.create! valid_attributes
      get :edit, {:id => talkabout.to_param}, valid_session
      expect(assigns(:talkabout)).to eq(talkabout)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Talkabout" do
        expect {
          post :create, {:talkabout => valid_attributes}, valid_session
        }.to change(Talkabout, :count).by(1)
      end

      it "assigns a newly created talkabout as @talkabout" do
        post :create, {:talkabout => valid_attributes}, valid_session
        expect(assigns(:talkabout)).to be_a(Talkabout)
        expect(assigns(:talkabout)).to be_persisted
      end

      it "redirects to the created talkabout" do
        post :create, {:talkabout => valid_attributes}, valid_session
        expect(response).to redirect_to(Talkabout.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved talkabout as @talkabout" do
        # Trigger the behavior that occurs when invalid params are submitted
        Talkabout.any_instance.stub(:save).and_return(false)
        post :create, {:talkabout => { "content" => "invalid value" }}, valid_session
        expect(assigns(:talkabout)).to be_a_new(Talkabout)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Talkabout.any_instance.stub(:save).and_return(false)
        post :create, {:talkabout => { "content" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested talkabout" do
        talkabout = Talkabout.create! valid_attributes
        # Assuming there are no other talkabouts in the database, this
        # specifies that the Talkabout created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Talkabout).to receive(:update).with({ "content" => "MyString" })
        put :update, {:id => talkabout.to_param, :talkabout => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested talkabout as @talkabout" do
        talkabout = Talkabout.create! valid_attributes
        put :update, {:id => talkabout.to_param, :talkabout => valid_attributes}, valid_session
        expect(assigns(:talkabout)).to eq(talkabout)
      end

      it "redirects to the talkabout" do
        talkabout = Talkabout.create! valid_attributes
        put :update, {:id => talkabout.to_param, :talkabout => valid_attributes}, valid_session
        expect(response).to redirect_to(talkabout)
      end
    end

    describe "with invalid params" do
      it "assigns the talkabout as @talkabout" do
        talkabout = Talkabout.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Talkabout.any_instance.stub(:save).and_return(false)
        put :update, {:id => talkabout.to_param, :talkabout => { "content" => "invalid value" }}, valid_session
        expect(assigns(:talkabout)).to eq(talkabout)
      end

      it "re-renders the 'edit' template" do
        talkabout = Talkabout.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Talkabout.any_instance.stub(:save).and_return(false)
        put :update, {:id => talkabout.to_param, :talkabout => { "content" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested talkabout" do
      talkabout = Talkabout.create! valid_attributes
      expect {
        delete :destroy, {:id => talkabout.to_param}, valid_session
      }.to change(Talkabout, :count).by(-1)
    end

    it "redirects to the talkabouts list" do
      talkabout = Talkabout.create! valid_attributes
      delete :destroy, {:id => talkabout.to_param}, valid_session
      expect(response).to redirect_to(talkabouts_url)
    end
  end

end
